export const questions=
[
    {
        questionText:"How are you feeling now-a-days?",
        answerOptions:[{answerText:"I do not feel sad",value:0},
        {answerText:"I feel sad",value:1},
        {answerText:"I feel sad all the time and i can't snap out of it",value:2},
        {answerText:"I am so sad and unhappy that i cannot stand it",value:3}],

    },

    {
        questionText:"What are your hopes for future?",
        answerOptions:[{answerText:"I am not particularly discouraged about the future.",value:0},
        {answerText:"I feel discouraged about the future",value:1},
        {answerText:"I feel i have nothing to look forward to ",value:2},
        {answerText:"I feel that future is hopeless and things cannot improve",value:3}],
    },

    {
        questionText:"Do you feel like a complete failure as a person?",
        answerOptions:[{answerText:"I do not feel like failure",value:0},
        {answerText:"I feel i have failed more than average person",value:1},
        {answerText:"As i look back on my life, all i see is lot of failure",value:2},
        {answerText:"I feel i am completely failure as a person",value:3}],
    },
    {
        questionText:"How much satisfaction or enjoyment do you get from activities you used to enjoy?",
        answerOptions:[{answerText:"I get as much satisfaction out of things as I used to.",value:0},
        {answerText:"I don't enjoy things the way I used to.",value:1},
        {answerText:"I don't get real satisfaction out of anything anymore.",value:2},
        {answerText:"I am dissatisfied or bored with everything",value:3}],
    },
    {
        questionText:"How often do you feel guilty?",
        answerOptions:[{answerText:"I don't feel particularly guilty",value:0},
        {answerText:"I feel guilty a good part of the time.",value:1},
        {answerText:" I feel quite guilty most of the time.",value:2},
        {answerText:"I feel guilty all of the time.",value:3}],
    },
    {
        questionText:"How do you feel about being punished?",
        answerOptions:[{answerText:"I don't feel I am being punished.",value:0},
        {answerText:"I feel I may be punished.",value:1},
        {answerText:"I expect to be punished.",value:2},
        {answerText:"I feel I am being punished.",value:3}],
    },
    {
        questionText:"How do you feel about yourself right now?",
        answerOptions:[{answerText:"I don't feel disappointed in myself.",value:0},
        {answerText:"I am disappointed in myself.",value:1},
        {answerText:"I am disgusted with myself.",value:2},
        {answerText:"I hate myself",value:3}],
    },
    {
        questionText:"To what extent do you blame yourself for your weaknesses or mistakes?",
        answerOptions:[{answerText:"I don't feel I am any worse than anybody else.",value:0},
        {answerText:"I am critical of myself for my weaknesses or mistakes.",value:1},
        {answerText:"I blame myself all the time for my faults.",value:2},
        {answerText:"CI blame myself for everything bad that happens.",value:3}],
    },
    {
        questionText:"Which statement best describes your thoughts about self-harm?",
        answerOptions:[{answerText:"I don't have any thoughts of killing myself.",value:0},
        {answerText:"I have thoughts of killing myself, but I would not carry them out.",value:1},
        {answerText:"I would like to kill myself.",value:2},
        {answerText:"I would kill myself if I had the chance",value:3}],
    },
    {
        questionText:"How has your crying behavior changed over time?",
        answerOptions:[{answerText:"I don't cry any more than usual.",value:0},
        {answerText:"I cry more now than I used to.",value:1},
        {answerText:"I cry all the time now.",value:2},
        {answerText:"I used to be able to cry, but now I can't cry even though I want to.",value:3}],
    },
    {
        questionText:"How often do you feel irritated or annoyed?",
        answerOptions:[{answerText:"I am no more irritated by things than I ever was.",value:0},
        {answerText:"I am slightly more irritated now than usual.",value:1},
        {answerText:"I am quite annoyed or irritated a good deal of the time.",value:2},
        {answerText:" I feel irritated all the time.",value:3}],
    },
    {
        questionText:"How interested are you in other people?",
        answerOptions:[{answerText:"I have not lost interest in other people.",value:0},
        {answerText:"I am less interested in other people than I used to be.",value:1},
        {answerText:"I have lost most of my interest in other people.",value:2},
        {answerText:" I have lost all of my interest in other people.",value:3}],
    },
     {
        questionText:"Do you have any worries regarding changing in your appearence?",
        answerOptions:[{answerText:"I don't feel that I look any worse than I used to.",value:0},
        {answerText:"I am worried that I am looking old or unattractive.",value:1},
        {answerText:"I feel there are permanent changes in my appearance that make me look unattractive",value:2},
        {answerText:" I believe that I look ugly.",value:3}],
    },
    {
        questionText:"How would you describe your current level of productivity and motivation?",
        answerOptions:[{answerText:"I can work about as well as before.",value:0},
        {answerText:"It takes an extra effort to get started at doing something.",value:1},
        {answerText:"I have to push myself very hard to do anything.",value:2},
        {answerText:" I can't do any work at all.",value:3}],
    },
     {
        questionText:"How has your sleep pattern changed recently?",
        answerOptions:[{answerText:"I can sleep as well as usual.",value:0},
        {answerText:"I don't sleep as well as I used to.",value:1},
        {answerText:"I wake up 1-2 hours earlier than usual and find it hard to get back to sleep.",value:2},
        {answerText:" I wake up several hours earlier than I used to and cannot get back to sleep.",value:3}],
    },
     {
        questionText:"Which of the following statements best describes your experience with fatigue?",
        answerOptions:[{answerText:"I don't get more tired than usual.",value:0},
        {answerText:"I get tired more easily than I used to.",value:1},
        {answerText:"I get tired from doing almost anything.",value:2},
        {answerText:"I am too tired to do anything.",value:3}],
    },
     {
        questionText:"Choose the statement that best describes your appetite?",
        answerOptions:[{answerText:"My appetite is no worse than usual.",value:0},
        {answerText:"My appetite is not as good as it used to be.",value:1},
        {answerText:"My appetite is much worse now.",value:2},
        {answerText:"I have no appetite at all anymore.",value:3}],
    },
     {
        questionText:"How much weight have you lost recently?",
        answerOptions:[{answerText:"I haven't lost much weight, if any, lately.",value:0},
        {answerText:"I have lost more than five pounds.",value:1},
        {answerText:"I have lost more than ten pounds.",value:2},
        {answerText:"I have lost more than fifteen pounds.",value:3}],
    },
];