# Generated by Django 4.2.6 on 2024-04-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
