# Generated by Django 4.2.6 on 2023-10-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
