# Generated by Django 4.2.6 on 2024-05-11 09:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctors_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[914, 927], upload_to='images'),
        ),
    ]
