# Generated by Django 5.0.6 on 2024-05-13 07:11

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_doctors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[914, 927], upload_to='images'),
        ),
    ]
