# Generated by Django 4.2.6 on 2024-05-21 00:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_doctors_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='documents',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
