# Generated by Django 4.2.6 on 2024-05-21 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_doctors_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='documents',
        ),
    ]
