# Generated by Django 4.2.6 on 2024-05-21 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0017_doctors_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='price',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='qualification',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='user',
            field=django_userforeignkey.models.fields.UserForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
