# Generated by Django 4.2.6 on 2023-10-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_newuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='CNIC',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
