# Generated by Django 4.2.6 on 2023-12-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctors_user'),
        ('user', '0006_alter_newuser_first_name_alter_newuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='CNIC',
        ),
        migrations.AddField(
            model_name='newuser',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, to='doctors.doctors'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
