# Generated by Django 4.2.6 on 2024-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_newuser_cnic_newuser_favorite_newuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
