# Generated by Django 4.2.6 on 2024-05-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_remove_message_room_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
