# Generated by Django 4.2.6 on 2024-05-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_paymenthistory_product_paymenthistory_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(upload_to='media')),
                ('book_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='doctor',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.product'),
        ),
    ]
